---
- name: deployment config
  k8s:
    definition: "{{ lookup('template', 'templates/deployment-config.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"

- name: service
  k8s:
    definition: "{{ lookup('template', 'templates/service.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"
