---
- name: secret
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/secret.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"

- name: image stream
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/image-stream.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"

- name: build config
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/build-config.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"

- name: deployment config
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/deployment-config.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"

- name: service
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/service.yaml') | from_yaml }}"
    host: "{{ openshift_host }}"
