version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00" # UTC
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
