---

apiVersion: v1
kind: Template
metadata:
  name: system-baseline
objects:

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: system-baseline
    labels:
      app: system-baseline
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - host-inventory
    - rbac

    optionalDependencies:
    - historical-system-profiles

    testing:
      iqePlugin: drift
    database:
      name: system-baseline
      version: 12

    jobs:
    - name: floorist
      schedule: ${FLOORIST_SCHEDULE}
      suspend: ${{FLOORIST_SUSPEND}}
      concurrencyPolicy: Forbid
      podSpec:
        image: ${FLOORIST_IMAGE}:${FLOORIST_IMAGE_TAG}
        env:
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: ${FLOORIST_BUCKET_SECRET_NAME}
              key: bucket
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: ${FLOORIST_BUCKET_SECRET_NAME}
              key: aws_region
        - name: AWS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ${FLOORIST_BUCKET_SECRET_NAME}
              key: endpoint
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ${FLOORIST_BUCKET_SECRET_NAME}
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ${FLOORIST_BUCKET_SECRET_NAME}
              key: aws_secret_access_key
        - name: FLOORPLAN_FILE
          value: "/tmp/floorplan/floorplan.yaml"
        - name: LOGLEVEL
          value: ${FLOORIST_LOGLEVEL}
        volumeMounts:
        - name: floorplan-volume
          mountPath: "/tmp/floorplan"
        volumes:
          - name: floorplan-volume
            configMap:
              name: floorplan
      resources:
          limits:
            cpu: "${CPU_LIMIT_FLOO}"
            memory: "${MEMORY_LIMIT_FLOO}"
          requests:
            cpu: "${CPU_REQUEST_FLOO}"
            memory: "${MEMORY_REQUEST_FLOO}"

    deployments:
    - name: backend-service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        imagePullPolicy: Always
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        volumes:
          - emptyDir: {}
            name: system-baseline-prometheus-data
        volumeMounts:
          - mountPath: /prometheus-data
            name: system-baseline-prometheus-data
        env:
          - name: APP_CONFIG
            value: gunicorn.conf.py
          - name: ENABLE_RBAC
            value: "${DRIFT_ENABLE_RBAC}"
          - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
            value: "${ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK}"
          - name: WEB_CONCURRENCY
            value: "4"
          - name: PATH_PREFIX
            value: /api/
          - name: APP_NAME
            value: system-baseline
          - name: ENABLE_PIPENV
            value: 'true'
          - name: prometheus_multiproc_dir
            value: /prometheus-data
          - name: DRIFT_SHARED_SECRET
            valueFrom:
              secretKeyRef:
                key: shared-secret
                name: drift-interpod-comms


- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: system-baseline
    labels:
      app: system-baseline
  spec:
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: system-baseline
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    targetCPUUtilizationPercentage: 50

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: floorplan
  data:
    floorplan.yaml: |
      - prefix: insights/system-baseline/baselines
        query: >-
          SELECT
            SB.ACCOUNT AS ACCOUNT_ID,
            SB.ID as BASELINE_ID,
            SBMS.SYSTEM_ID AS ASSOCIATED_SYSTEM_ID FROM SYSTEM_BASELINES SB
            LEFT OUTER JOIN SYSTEM_BASELINE_MAPPED_SYSTEMS SBMS ON SBMS.SYSTEM_BASELINE_ID  = SB.ID;

parameters:
  - name: DRIFT_ENABLE_RBAC
    description: enable rbac. needs to be "True" or "False".
    value: "True"
  - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
    description: enable the smart mgmt entitlement check on requests. Needs to be "True" or "False".
    value: "False"
  - name: IMAGE_TAG
    description: image tag to pull
  - name: IMAGE
    description: image name
    value: quay.io/cloudservices/system-baseline-backend
  - name: MIN_REPLICAS
    description: minimum pod replicas for horizontal pod autoscaler
    value: "3"
  - name: MAX_REPLICAS
    description: maximum pod replicas for horizontal pod autoscaler
    value: "3"
  - name: CPU_LIMIT
    value: 700m
  - name: MEMORY_LIMIT
    value: 1Gi
  - name: CPU_REQUEST
    value: 100m
  - name: MEMORY_REQUEST
    value: 512Mi
  - description: ClowdEnv Name
    name: ENV_NAME
  - name: CLOWDER_ENABLED
    value: "true"
  - name: FLOORIST_SCHEDULE
    description: Cronjob schedule definition
    required: true
    value: '20 11 * * *'
  - name: FLOORIST_SUSPEND
    description: Disable Floorist cronjob execution
    required: true
    value: 'true'
  - description: Floorist image name
    name: FLOORIST_IMAGE
    value: quay.io/cloudservices/floorist
  - description: Floorist Image tag
    name: FLOORIST_IMAGE_TAG
    required: true
    value: latest
  - description: bucket secret name
    name: FLOORIST_BUCKET_SECRET_NAME
    required: true
    value: dummy-secret
  - name: FLOORIST_LOGLEVEL
    description: Floorist loglevel config
    value: 'INFO'
