---

apiVersion: v1
kind: Template
metadata:
  name: system-baseline
objects:

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: migration
  spec:
    appName: system-baseline
    jobs:
      - baseline-migration

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: system-baseline
    labels:
      app: system-baseline
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - host-inventory
    - rbac
    - drift
    - historical-system-profiles

    testing:
      iqePlugin: drift
    database:
      name: system-baseline-db
      version: 12
    jobs:
    - name: baseline-migration
      podSpec:
        imagePullPolicy: Always
        image: ${IMAGE}:${IMAGE_TAG}
        volumes:
          - emptyDir: {}
            name: system-baseline-prometheus-data
        volumeMounts:
          - mountPath: /prometheus-data
            name: system-baseline-prometheus-data
        env:
          - name: APP_CONFIG
            value: gunicorn.conf.py
          - name: ENABLE_RBAC
            value: "${DRIFT_ENABLE_RBAC}"
          - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
            value: "${ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK}"
          - name: WEB_CONCURRENCY
            value: "4"
          - name: PATH_PREFIX
            value: /api/
          - name: APP_NAME
            value: system-baseline
          - name: ENABLE_PIPENV
            value: 'true'
          - name: prometheus_multiproc_dir
            value: /prometheus-data
          - name: IS_MIGRATION
            value: 'true'
          - name: DRIFT_SHARED_SECRET
            valueFrom:
              secretKeyRef:
                key: shared-secret
                name: drift-interpod-comms

    deployments:
    - name: backend-service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        imagePullPolicy: Always
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        volumes:
          - emptyDir: {}
            name: system-baseline-prometheus-data
        volumeMounts:
          - mountPath: /prometheus-data
            name: system-baseline-prometheus-data
        env:
          - name: APP_CONFIG
            value: gunicorn.conf.py
          - name: ENABLE_RBAC
            value: "${DRIFT_ENABLE_RBAC}"
          - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
            value: "${ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK}"
          - name: WEB_CONCURRENCY
            value: "4"
          - name: PATH_PREFIX
            value: /api/
          - name: APP_NAME
            value: system-baseline
          - name: ENABLE_PIPENV
            value: 'true'
          - name: prometheus_multiproc_dir
            value: /prometheus-data
          - name: DRIFT_SHARED_SECRET
            valueFrom:
              secretKeyRef:
                key: shared-secret
                name: drift-interpod-comms

- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: system-baseline
    labels:
      app: system-baseline
  spec:
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: system-baseline
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    targetCPUUtilizationPercentage: 50

parameters:
  - name: DRIFT_ENABLE_RBAC
    description: enable rbac. needs to be "True" or "False".
    value: "True"
  - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
    description: enable the smart mgmt entitlement check on requests. Needs to be "True" or "False".
    value: "False"
  - name: IMAGE_TAG
    description: image tag to pull
    value: latest
  - name: IMAGE
    description: image name
    value: quay.io/cloudservices/system-baseline-backend
  - name: MIN_REPLICAS
    description: minimum pod replicas for horizontal pod autoscaler
    value: "1"
  - name: MAX_REPLICAS
    description: maximum pod replicas for horizontal pod autoscaler
    value: "1"
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 500Mi
  - name: CPU_REQUEST
    value: 100m
  - name: MEMORY_REQUEST
    value: 300Mi
  - description: ClowdEnv Name
    name: ENV_NAME
  - name: CLOWDER_ENABLED
    value: "true"
