---
apiVersion: v1
kind: Template
metadata:
  name: drift

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: drift
    labels:
      app: drift
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - host-inventory
    - rbac
    - system-baseline
    - historical-system-profiles
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /mgmt/v0/status
            port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: {MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        volumes:
          - emptyDir: {}
            name: drift-prometheus-data
        volumeMounts:
          - mountPath: /prometheus-data
            name: drift-prometheus-data
        env:
          - name: APP_CONFIG
            value: gunicorn.conf.py
          - name: ENABLE_RBAC
            value: "${DRIFT_ENABLE_RBAC}"
          - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
            value: "${ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK}"
          - name: WEB_CONCURRENCY
            value: "4"
          - name: PATH_PREFIX
            value: /api/
          - name: APP_NAME
            value: drift
          - name: ENABLE_PIPENV
            value: 'true'
          - name: prometheus_multiproc_dir
            value: /prometheus-data
          - name: DRIFT_SHARED_SECRET
            valueFrom:
              secretKeyRef:
                key: shared-secret
                name: drift-interpod-comms

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: drift-backend
    name: drift-backend
    annotations:
      prometheus.io/path: /mgmt/v0/metrics
      prometheus.io/port: '8080'
      prometheus.io/scrape: 'true'
  spec:
    type: ClusterIP
    selector:
      deploymentconfig: drift-backend
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080

- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: drift-backend
    labels:
      app: drift-backend
  spec:
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: drift-backend
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    targetCPUUtilizationPercentage: 50

parameters:
  - name: DRIFT_ENABLE_RBAC
    description: enable rbac. needs to be "True" or "False".
    value: "True"
  - name: ENABLE_SMART_MANGEMENT_ENTITLEMENT_CHECK
    description: enable the smart mgmt entitlement check on requests. Needs to be "True" or "False".
    value: "False"
  - name: IMAGE_TAG
    description: image tag to pull
    value: latest
  - name: IMAGE
    description: image name
    value: quay.io/cloudservices/drift-backend
  - name: MIN_REPLICAS
    description: minimum pod replicas for horizontal pod autoscaler
    value: "2"
  - name: MAX_REPLICAS
    description: maximum pod replicas for horizontal pod autoscaler
    value: "2"
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 500Mi
  - name: CPU_REQUEST
    value: 100m
  - name: MEMORY_REQUEST
    value: 300Mi
