[tool.black]
line-length=100
target-version=["py39"]

[tool.isort]
profile = "black"
atomic=true
line_length = 100
lines_after_imports=2
lines_between_types=1
known_third_party=[
    "pytest",
    "click",
]
known_first_party=["system-baseline-backend"]

[tool.coverage.run]
branch = false
source = ["system-baseline-backend"]
omit = ["system-baseline-backend/tests/*",]

[tool.coverage.paths]
source = ["system-baseline-backend/"]

[tool.coverage.report]
fail_under = 73
skip_covered = true
show_missing = true

[tool.pytest.ini_options]
minversion = "6.2.1"
addopts = "-s --tb=native --cov=."
testpaths = "./tests"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    'ignore:function ham\(\) is deprecated:DeprecationWarning'
    ]

[tool.poetry]
name = "system-baseline-backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.9"
connexion = {extras = ["swagger-ui"], version = "==2.5.1"}
Flask = "==1.1.4"
gunicorn = "*"
prometheus_client = "*"
boto3 = "*"
watchtower = "*"
flask-sqlalchemy = "*"
sqlalchemy = "<2"
alembic = "*"
flask-script = "*"
flask-migrate = "*"
bitmath = "*"
jsonpatch = "*"
insights-core = "*"
kerlescan = {git = "https://github.com/RedHatInsights/kerlescan.git", rev = "0.102", develop = true}
app-common-python = "*"
unleashclient = "*"
jsonschema = "==3.2.0"
markupsafe = "==2.0.1"
psycopg2 = "*"


[tool.poetry.group.dev.dependencies]
openapi-spec-validator = "*"
coverage = "*"
flake8 = "*"
mock = "*"
responses = "*"
yamllint = "==1.26.0"
black = "==21.6b0"
ipdb = "*"
podman-compose = "*"
python-semantic-release = "*"
pytest = "*"
pytest-cov = "*"
pytest-flask = "*"
pytest-black = "*"
pytest-mock = "*"
toml = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
