# a basic report without multivalue facts
[report1]
expected_output_path = "tests/reports/outputs/report1.json"
systems_path = "tests/reports/inputs/inventory/report1-systems.json"
profiles_path = "tests/reports/inputs/inventory/report1-system_profiles.json"
baselines_path = "tests/reports/inputs/baselines/report1-baselines.json"
hsps_path = "tests/reports/inputs/hsps/report1-hsps.json"

