"""add not null constraint on account column

Revision ID: 46636756274e
Revises: 9a630ad809d9
Create Date: 2021-04-09 16:49:29.663271

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "46636756274e"
down_revision = "9a630ad809d9"
branch_labels = None
depends_on = None


def upgrade():
    # Delete any existing rows with null account column. These shouldn't
    # be accessible and will cause the not null constraint to fail to be
    # added in the alter_column below.
    op.execute("DELETE FROM historical_system_profiles WHERE account IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "historical_system_profiles",
        "account",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "historical_system_profiles",
        "account",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    # ### end Alembic commands ###
