"""Change account not-null arg to nullable, since we're not using account anymore

Revision ID: 8b45ee66c00b
Revises: 687d72865512
Create Date: 2023-08-16 11:28:08.106270

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "8b45ee66c00b"
down_revision = "687d72865512"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_system_profiles", schema=None) as batch_op:
        batch_op.alter_column("account", existing_type=sa.VARCHAR(length=10), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_system_profiles", schema=None) as batch_op:
        batch_op.alter_column("account", existing_type=sa.VARCHAR(length=10), nullable=False)

    # ### end Alembic commands ###
