---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: drift-backend
  name: drift-backend
  namespace: "{{ project }}"
spec:
  type: ClusterIP
  selector:
    deploymentconfig: drift-backend
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
