---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: drift-backend
  name: drift-backend
  namespace: "{{ project }}"
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  source:
    git:
      ref: master
      uri: 'https://github.com/RedHatInsights/drift-backend.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: ENABLE_PIPENV
          value: 'true'
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Source
  resources:
    limits:
      cpu: 50m
      memory: 500Mi
  output:
    to:
      kind: ImageStreamTag
      name: 'drift-backend:latest'
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: GitHub
      github:
        secretReference:
          name: github-webhook-secret
