API_VERSION_PREFIX = "/v0"
AUTH_HEADER_NAME = 'X-RH-IDENTITY'
FACT_NAMESPACE = "inventory"
INVENTORY_SVC_HOSTS_ENDPOINT = '/r/insights/platform/inventory/api/v1/hosts/%s?per_page=%s'
MAX_UUID_COUNT = 20
MOCK_FACT_NAMESPACE = 'mockfacts'
MOCK_FACTS_FILE = 'drift/mock_data/mockfacts.json'
SYSTEM_ID_KEY = 'id'

COMPARISON_SAME = "SAME"
COMPARISON_DIFFERENT = "DIFFERENT"
COMPARISON_INCOMPLETE_DATA = "INCOMPLETE_DATA"
