"""empty message

Revision ID: 30f9b89dc527
Revises: 397f7f183459
Create Date: 2023-12-18 15:52:46.476775

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "30f9b89dc527"
down_revision = "397f7f183459"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_baseline_mapped_systems",
        "account",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "system_baselines", "account", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_baselines", "account", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column(
        "system_baseline_mapped_systems",
        "account",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
