"""add map to system ids

Revision ID: 63a89136a199
Revises: 16a84bebd064
Create Date: 2021-03-24 22:32:00.267482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63a89136a199"
down_revision = "16a84bebd064"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_baseline_mapped_systems",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account", sa.String(length=10), nullable=False),
        sa.Column("system_baseline_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("system_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["system_baseline_id"], ["system_baselines.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "system_baseline_id", "system_id", name="_system_baseline_mapped_system_uc"
        ),
    )
    op.create_index(
        op.f("ix_system_baseline_mapped_systems_system_id"),
        "system_baseline_mapped_systems",
        ["system_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_system_baseline_mapped_systems_system_id"),
        table_name="system_baseline_mapped_systems",
    )
    op.drop_table("system_baseline_mapped_systems")
    # ### end Alembic commands ###
