"""empty message

Revision ID: 687d72865512
Revises: e07ac5a2cd11
Create Date: 2023-08-15 15:50:13.244737

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "687d72865512"
down_revision = "e07ac5a2cd11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_system_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("groups", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_system_profiles", schema=None) as batch_op:
        batch_op.drop_column("groups")

    # ### end Alembic commands ###
