"""added captured_on column

Revision ID: 6c97901967f3
Revises: 5d803f844a03
Create Date: 2020-04-22 14:19:59.782594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c97901967f3"
down_revision = "5d803f844a03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_system_profiles",
        sa.Column("captured_on", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("historical_system_profiles", "captured_on")
    # ### end Alembic commands ###
