"""empty message

Revision ID: 9a630ad809d9
Revises: 9b6b2ca8d235
Create Date: 2020-06-29 17:53:15.779852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a630ad809d9"
down_revision = "9b6b2ca8d235"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("historical_system_profiles", "modified_on")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_system_profiles",
        sa.Column(
            "modified_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
