"""index account

Revision ID: c6be183101f1
Revises: e07ac5a2cd11
Create Date: 2022-08-09 14:37:17.406967

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6be183101f1"
down_revision = "e07ac5a2cd11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_historical_system_profiles_account"),
        "historical_system_profiles",
        ["account"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_historical_system_profiles_account"), table_name="historical_system_profiles"
    )
    # ### end Alembic commands ###
