"""empty message

Revision ID: 397f7f183459
Revises: 3eddafc4cb9f
Create Date: 2023-08-17 16:15:13.887984

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "397f7f183459"
down_revision = "3eddafc4cb9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_baseline_mapped_systems",
        sa.Column("groups", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_baseline_mapped_systems", "groups")
    # ### end Alembic commands ###
