{
 "title": "Drift",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rds_datasource", "label": "rds_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"drift\"}[$__range]))"
    }
   ]
  },
  {
   "title": "2xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\", status=\"2xx\"}[$__range])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Baseline requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_baseline_service_requests_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "HSP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_hsp_service_requests_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "Inventory requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_inventory_service_requests_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "RBAC requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_rbac_service_requests_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "Comparison report requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_comparison_report_requests_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "Containers restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"drift-.*\"})"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\", status=\"5xx\"}[$__range])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\", status=\"4xx\"}[$__range])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Baseline exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_baseline_service_exceptions_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "HSP exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_hsp_service_exceptions_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "Inventory exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_inventory_service_exceptions_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "RBAC exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_rbac_exceptions_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "API exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(drift_api_exceptions_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "Golden signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Outbound traffic (req/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drift_baseline_service_requests_count{}[$interval]))",
     "legendFormat": "baseline"
    },
    {
     "expr": "sum(rate(drift_hsp_service_requests_count{}[$interval]))",
     "legendFormat": "hsp"
    },
    {
     "expr": "sum(rate(drift_inventory_service_requests_count{}[$interval]))",
     "legendFormat": "inventory"
    },
    {
     "expr": "sum(rate(drift_rbac_service_requests_count{}[$interval]))",
     "legendFormat": "rbac"
    }
   ]
  },
  {
   "title": "Outbound latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(drift_baseline_service_requests_sum{}[$interval])) / sum(rate(drift_baseline_service_requests_count{}[$interval]))",
     "legendFormat": "baseline"
    },
    {
     "expr": "1000 * sum(rate(drift_hsp_service_requests_sum{}[$interval])) / sum(rate(drift_hsp_service_requests_count{}[$interval]))",
     "legendFormat": "hsp"
    },
    {
     "expr": "1000 * sum(rate(drift_inventory_service_requests_sum{}[$interval])) / sum(rate(drift_inventory_service_requests_count{}[$interval]))",
     "legendFormat": "inventory"
    },
    {
     "expr": "1000 * sum(rate(drift_rbac_service_requests_sum{}[$interval])) / sum(rate(drift_rbac_service_requests_count{}[$interval]))",
     "legendFormat": "rbac"
    }
   ]
  },
  {
   "title": "Inbound traffic (req/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drift_comparison_report_requests_count{}[$interval]))",
     "legendFormat": "comparison_report"
    }
   ]
  },
  {
   "title": "Inbound latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(drift_comparison_report_requests_sum{}[$interval])) / sum(rate(drift_comparison_report_requests_count{}[$interval]))",
     "legendFormat": "comparison_report"
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"drift-.*\"}[$interval])) by (container)/ sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"drift-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=~\"drift-.+|system-baseline-.+|historical-system-profiles-.+\",container=~\"drift-.+|system-baseline-.+|historical-system-profiles-.+\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Outbound exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drift_baseline_service_exceptions_total{}[$interval]))",
     "legendFormat": "baseline"
    },
    {
     "expr": "sum(rate(drift_hsp_service_exceptions_total{}[$interval]))",
     "legendFormat": "hsp"
    },
    {
     "expr": "sum(rate(drift_inventory_service_exceptions_total{}[$interval]))",
     "legendFormat": "inventory"
    },
    {
     "expr": "sum(rate(drift_rbac_exceptions_total{}[$interval]))",
     "legendFormat": "rbac"
    }
   ]
  },
  {
   "title": "Traffic status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"drift\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Inbound exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drift_comparison_report_exceptions_total{}[$interval]))",
     "legendFormat": "comparison_report"
    },
    {
     "expr": "sum(rate(drift_api_exceptions_total{}[$interval]))",
     "legendFormat": "api"
    }
   ]
  },
  {
   "title": "Containers restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"drift-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Systems compared",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(drift_systems_compared_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_topic_sum_lag{group=~\"hsp-.*\"}) by (group, topic)",
     "legendFormat": "{{topic}} {{group}}"
    }
   ]
  },
  {
   "title": "RDS data capacity usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_fileSys_usedPercent{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance, mount_point)",
     "legendFormat": "{{exported_instance}}: {{mount_point}}"
    }
   ]
  },
  {
   "title": "RDS CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rdsosmetrics_processList_cpuUsedPc{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}, \"db_user\", \"$1\", \"name\", \"postgres: ([^ ]+) .+\")) by (exported_instance, db_user)",
     "legendFormat": "{{exported_instance}}: {{db_user}}"
    }
   ]
  },
  {
   "title": "RDS memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_memory_total{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "total memory: {{exported_instance}}"
    },
    {
     "expr": "sum(rdsosmetrics_memory_free{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "free memory: {{exported_instance}}"
    },
    {
     "expr": "sum(rdsosmetrics_memory_dirty{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "dirty memory: {{exported_instance}}"
    },
    {
     "expr": "sum(rdsosmetrics_memory_active{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "active memory: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "RDS load avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_one{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}: Load Avg 1 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_five{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}: Load Avg 5 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_fifteen{exported_instance=~\"historical-system-profiles-.*|system-baseline-.*\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}: Load Avg 15 min"
    }
   ]
  },
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Performance timing Quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drift_performance_timing_bucket[5m])) by (le, method, method_part))",
     "legendFormat": "{{method}}::{{method_part}}"
    }
   ]
  },
  {
   "title": "System Profile Requests",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(drift_performance_timing_bucket{method_part=\"api_system_profile_requests\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Baseline Requests",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(drift_performance_timing_bucket{method_part=\"api_baseline_requests\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "3scale API Time taken",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"drift\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HSP Requests",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(drift_performance_timing_bucket{method_part=\"api_hsp_requests\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}