---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: drift-backend
  name: drift-backend
  namespace: "{{ project }}"
spec:
  replicas: 1
  selector:
    deploymentconfig: drift-backend
  strategy:
    type: Rolling
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: drift-backend
        deploymentconfig: drift-backend
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: APP_CONFIG
              value: gunicorn.conf.py
            - name: PATH_PREFIX
              value: /api/
            - name: APP_NAME
              value: drift
            - name: ENABLE_PIPENV
              value: 'true'
            - name: prometheus_multiproc_dir
              value: /prometheus-data
            - name: INVENTORY_SVC_URL
              value: "{{ inventory_svc_url }}"
          readinessProbe:
            httpGet:
              path: /mgmt/v0/status
              port: 8080
          livenessProbe:
            httpGet:
              path: /mgmt/v0/status
              port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          image: "{{ project }}/drift-backend:latest"
          imagePullPolicy: Always
          name: drift-backend
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /prometheus-data
              name: drift-prometheus-data
      volumes:
        - emptyDir: {}
          name: drift-prometheus-data
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - drift-backend
        from:
          kind: ImageStreamTag
          name: 'drift-backend:latest'
          namespace: "{{ project }}"
