---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drift-backend
  namespace: drift-prod
  labels:
    app: drift-backend
spec:
  maxReplicas: 12
  minReplicas: 6
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: drift-backend
  targetCPUUtilizationPercentage: 50
