---
- name: Deploy drift-backend to Openshift
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    environment: "{{ project.split('-')[1] }}"
  vars_files:
    - "vars/{{ environment }}.yml"
  roles:
    - drift-backend
