---
- name: Deploy drift-backend to Openshift
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - vars/secrets.yml
  vars:
    deployment_state: present
    project: drift-ci
  roles:
    - drift-backend
