name: Regular base image update check
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Base Image Update Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install skopeo
        run: sudo apt-get install -y skopeo
      - name: Check change
        run: |
          docker run --rm --entrypoint sh -u 0 quay.io/cloudservices/drift-backend:latest -c \
            'microdnf upgrade -y > /dev/null; rpm -qa | sort | sha256sum' \
            > .baseimagedigest
      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add .baseimagedigest
          git commit -m "chore(image): update and rebuild image" || echo "No new changes"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'chore(image): update base image'
          token: ${{ secrets.GH_PAT }} # uses Personal Access Token so the creation of PR triggers other workflows
